branch-defaults:
  master:
    environment: snapflix
    group_suffix: null
global:
  application_name: api.snapflix.com
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 1.12.6
  default_region: us-west-1
  profile: eb-cli
  repository: null
  sc: git
