branch-defaults:
  master:
    environment: express-server-api-dev
global:
  application_name: express-server-api
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-1
  profile: eb-cli
  repository: null
  sc: git
